### ISSUE TITLE
Ikea - na stránkách se nevykreslí extenze

### ISSUE THREAD

**Issue by MartinaGelnerova** [theodik/hlidac-shopu#867]
https://www.ikea.com/cz/cs/p/sockerbit-ulozna-krabice-s-vikem-sedo-zelena-00514066/
```
content.js:24897 Error: Element to add chart not found
    at Ikea.inject (content.js:23512:15)
    at renderHTML (content.js:24840:12)
    at render (content.js:24890:11)
    at Ikea.scheduleRendering (content.js:23523:7)
    at async main (content.js:24921:5)
```

**Comment by rarous** [comment]
Opraveno v příštím release
